# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
#:schema = https://yazi-rs.github.io/schemas/keymap.json
# CUSTOM KEYMAP
[mgr]

prepend_keymap = [
	# Goto
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "Go home" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Go ~/.config" },
	{ on = [ "g", "d" ],       run = "cd ~/dotfiles",   desc = "Go ~/dotfiles" },
	{ on = [ "g", "a" ],       run = "cd ~/Documents/AUS/",   desc = "Go /AUS" },
	{ on = [ "g", "v" ],       run = "cd ~/Videos/grabaciones/",   desc = "Go /Videos" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Jump interactively" },
	{ on = [ "g", "f" ],       run = "follow",           desc = "Follow hovered symlink" },

  #CHMOD plugin
	{ on = [ "c", "m" ],       run = "plugin chmod",           desc = "Chmod on selected files" },

  # MOUNT plugin
  { on = [ "M" ],            run = "plugin mount" },
  
  # OUCH compression
  { on = [ "C" ],            run = "plugin ouch",            desc = "Compress with ouch"},
]

# OUCH preview
[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
  { mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
]

# OUCH decompression
[opener]
extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
