"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_cyan)\
$os\
$username\
[](bg:color_bg0 fg:color_cyan)\
$directory\
[](fg:color_bg0 bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_purple)\
$c\
$dotnet\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_purple bg:color_pink)\
$docker_context\
$conda\
[](fg:color_pink bg:color_pink)\
$time\
[ ](fg:color_pink)\
$line_break$character"""

palette = 'eldritch'

[palettes.eldritch]
color_bg = '#212337'
color_bg0 = '#323449'
color_bgAlt = '#1e2124'
color_bgHighlight = '#3c4048'
color_fg = '#ebfafa'
color_grey = '#7b8496'
color_blue = '#7081d0'
color_green = '#37f499'
color_cyan = '#04d1f9'
color_red = '#f16c75'
color_yellow = '#f1fc79'
color_magenta = '#ff5ef1'
color_pink = '#f265b5'
color_orange = '#f7c67f'
color_purple = '#a48cf2'

[palettes.cyberdream]
color_bg = '#16181a'
color_bg0 = '#161616'
color_bgAlt = '#1e2124'
color_bgHighlight = '#3c4048'
color_fg = '#ffffff'
color_grey = '#7b8496'
color_blue = '#5ea1ff'
color_green = '#5eff6c'
color_cyan = '#5ef1ff'
color_red = '#ff6e5e'
color_yellow = '#f1ff5e'
color_magenta = '#ff5ef1'
color_pink = '#ff5ea0'
color_orange = '#ffbd5e'
color_purple = '#bd5eff'

[os]
disabled = false
style = "bg:color_cyan fg:color_bg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽 "
Gentoo = "󰣨"
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = ""
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "bold bg:color_cyan fg:color_bg"
style_root = "bold bg:color_cyan fg:color_bg" 
format = '[ Nick ニック ]($style)'

[directory]
style = "fg:color_cyan bg:color_bg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
# https://www.nerdfonts.com/cheat-sheet
[directory.substitutions]
"~" = " "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰝚 "
"Pictures" = "  "
"Developer" = " 󰘦 "
"/GO" = "/ 󰟓 "
"/JS" = "/  "
"/C" = "/  "
"/Dotnet" = "/ "
"/ReactJs" = "/ "

[git_branch]
symbol = "  "
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_bg bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_bg bg:color_green)]($style)'

[nodejs]
symbol = "\ue719"
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[c]
symbol = "  "
style = "bg:color_purple" 
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'


[dotnet]
symbol = "  "
style = "bg:color_purple" 
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'
detect_extensions = ['csproj', 'fsproj', 'xproj']
heuristic = false

[rust]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[golang]
symbol = " 󰟓  "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[php]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[java]
symbol = "  "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[kotlin]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[haskell]
symbol = "  "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[python]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[docker_context]
symbol = " "
style = "bg:color_grey"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bgAlt)]($style)'

[conda]
style = "bg:color_bg0"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_pink)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_pink"
format = '[[  $time ](fg:color_fg bg:color_pink)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
