"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg)\
$os\
$username\
[](bg:color_purple fg:color_bg)\
$directory\
[](fg:color_purple bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_bg)\
$c\
$dotnet\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg bg:color_bg)\
$docker_context\
[ ](fg:color_bg)\
$line_break$character"""

palette = 'cyberdream'

[palettes.solarized_dark]
color_bg = '#00141a'
color_bg0 = '#00141a'
color_bgAlt = '#1e2124'
color_bgHighlight = '#002731'
color_fg = '#fcf4dc'
color_grey = '#465a61'
color_grey_alt = '#718080'
color_blue = '#2075c7'
color_green = '#728905'
color_dark_green = '#002834'
color_cyan = '#259185'
color_red = '#d01b24'
color_yellow = '#a57705'
color_magenta = '#c61b6e'
color_pink = '#c61b6e'
color_purple = '#5856b9'

[palettes.eldritch]
color_bg = '#212337'
color_bg0 = '#323449'
color_bgAlt = '#1e2124'
color_bgHighlight = '#3c4048'
color_fg = '#ebfafa'
color_grey = '#7b8496'
color_blue = '#7081d0'
color_green = '#37f499'
color_cyan = '#04d1f9'
color_red = '#f16c75'
color_yellow = '#f1fc79'
color_magenta = '#ff5ef1'
color_pink = '#f265b5'
color_orange = '#f7c67f'
color_purple = '#a48cf2'

[palettes.rose-pine]
color_bg = '#191724'
color_bg0 = '#26233a'
color_bgAlt = '#1e2124'
color_bgHighlight = '#403d52'
color_fg = '#e0def4'
color_grey = '#524f67'
color_blue = '#9ccfd8'
color_green = '#31748f'
color_cyan = '#ebbcba'
color_red = '#eb6f92'
color_yellow = '#f6c177'
color_magenta = '#c4a7e7'
color_pink = '#f265b5'
color_orange = '#f6c177'
color_purple = '#c4a7e7'

[palettes.cyberdream]
color_bg = '#080808'
color_bg0 = '#161616'
color_bgAlt = '#1e2124'
color_bgHighlight = '#3c4048'
color_fg = '#ffffff'
color_grey = '#7b8496'
color_blue = '#5ea1ff'
color_green = '#5eff6c'
color_cyan = '#5ef1ff'
color_red = '#ff6e5e'
color_yellow = '#f1ff5e'
color_magenta = '#ff5ef1'
color_pink = '#ff5ea0'
color_orange = '#ffbd5e'
color_purple = '#bd5eff'

[os]
disabled = true
style = "bg:color_bg fg:color_blue"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽 "
Gentoo = "󰣨"
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = ""
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "bold bg:color_bg fg:color_green"
style_root = "bold bg:color_bg fg:color_green" 
format = '[   Nick ニック]($style)'

[directory]
style = "bold fg:color_bg bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰝚 "
"Pictures" = "  "
"Developer" = "  "
"Assembly" = "  "
"/C" = "/  "
"/Dotnet" = "/  "
"/GO" = "/ 󰟓 "
"/Haskell" = "/  "
"/JS" = "/  "
"/Lua" = "/  "
"/ReactJs" = "/  "

[git_branch]
symbol = " "
style = "bg:color_dark_green"
format = '[[ $symbol $branch ](fg:color_bg bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](bold fg:color_bg bg:color_green)]($style)'

[nodejs]
symbol = "\ue719"
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_green bg:color_bg)]($style)'

[c]
symbol = " "
style = "bg:color_bg" 
format = '[[ $symbol( $version) ](fg:color_cyan bg:color_bg)]($style)'


[dotnet]
symbol = " "
style = "bg:color_bg" 
format = '[[ $symbol( $version) ](fg:color_purple bg:color_bg)]($style)'
detect_extensions = ['csproj', 'fsproj', 'xproj']
heuristic = false

[rust]
symbol = ""
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_red bg:color_bg)]($style)'

[golang]
symbol = "󰟓 "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_blue bg:color_bg)]($style)'

[php]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_blue bg:color_bg)]($style)'

[java]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_red bg:color_bg)]($style)'

[kotlin]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[haskell]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_purple bg:color_bg)]($style)'

[python]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_yellow bg:color_purple)]($style)'

[docker_context]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:color_bg bg:color_blue)]($style)'

[conda]
style = "bg:color_bg0"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_pink)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_red"
format = '[[  $time ](fg:color_bg bg:color_yellow)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:color_green)'
error_symbol = '[ ](bold fg:color_red)'
vimcmd_symbol = '[󱞥 ](bold fg:color_blue)'
vimcmd_replace_one_symbol = '[󱞥 ](bold fg:color_purple)'
vimcmd_replace_symbol = '[󱞥 ](bold fg:color_purple)'
vimcmd_visual_symbol = '[󱞥 ](bold fg:color_yellow)'
