# ~/.config/starship.toml

add_newline = false
command_timeout = 1000

format = """
$character\
$os$hostname\
$directory\
$git_branch\
$git_status \
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$docker_context\
$cmd_duration
[➜](bold purple) """


continuation_prompt = '▶▶ '

[character]
success_symbol = "🚀 "
error_symbol = "🔥 "

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = 'took: [$duration](bold yellow)'

# ---


[os]
format = '🤖 '   
disabled = false

[os.symbols]
Macos = '󰀵'
Redhat = "🤖  "
Linux = "🤖 "
# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false
ssh_symbol = " "

# Shows current directory
[directory]
truncation_length = 3
fish_style_pwd_dir_length=2
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = " "
format = 'on [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '


# ---

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = " "

[package]
format = '[$symbol$version](208 bold) '

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rlang]
symbol = "󰟔 "

[rust]
symbol = " "

[scala]
symbol = " "
